bc_app_wallet_transaction.index:
    pattern:  /txs
    defaults: { _controller: "bc_app_wallet_transaction.index_controller" }
    requirements: { _method: get }

bc_app_wallet_transaction.new:
    pattern:  /txs/new
    defaults: { _controller: "bc_app_wallet_transaction.show_new_controller" }
    requirements: { _method: get }

bc_app_wallet_transaction.create:
    pattern:  /txs/new
    defaults: { _controller: "bc_app_wallet_transaction.create_controller" }
    requirements: { _method: post }