parameters:
    bc_app_common_homepage.homepage_controller.class: BlockCypher\AppCommon\Infrastructure\AppCommonBundle\Controller\Homepage\Home

services:
    bc_app_common_homepage.homepage_controller:
        class: %bc_app_common_homepage.homepage_controller.class%
        arguments:
          - @templating
          - @translator
          - @session