bc_app_common_security:
    resource: "@BlockCypherAppCommonInfrastructureAppCommonBundle/Resources/config/routing/security.yml"

bc_app_common_homepage:
    resource: "@BlockCypherAppCommonInfrastructureAppCommonBundle/Resources/config/routing/homepage.yml"