parameters:

    bc_app_wallet_homepage.homepage_controller.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Homepage\Home

services:

    bc_app_wallet_homepage.homepage_controller:
        class: %bc_app_wallet_homepage.homepage_controller.class%
        arguments:
          - @security.token_storage
          - @templating
          - @translator
          - @session