parameters:

    # controllers

    bc_app_wallet_transaction.index_controller.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Transaction\Index
    bc_app_wallet_transaction.show_new_controller.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Transaction\ShowNew
    bc_app_wallet_transaction.create_controller.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Transaction\Create

    # sercice facades

    # services

    # repositories

    bc_app_wallet_transaction.encrypted_transaction_repository.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\FlywheelEncryptedTransactionRepository
    bc_app_wallet_transaction.transaction_repository.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\FlywheelTransactionRepository

    # command handlers

    bc_app_wallet_transaction.create_transaction_command_handler.class: BlockCypher\AppWallet\App\Command\CreateTransactionCommandHandler

    # form factories

    bc_app_wallet_transaction.transaction_form_factory.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Form\Transaction\TransactionFormFactory

services:

    # controllers

    bc_app_wallet_transaction.index_controller:
        class: %bc_app_wallet_transaction.index_controller.class%
        arguments:
          - @security.token_storage
          - @templating
          - @translator
          - @session
          - @bc_app_wallet_wallet.wallet_service_facade

    bc_app_wallet_transaction.show_new_controller:
        class: %bc_app_wallet_transaction.show_new_controller.class%
        arguments:
          - @security.token_storage
          - @templating
          - @translator
          - @session
          - @bc_app_wallet_transaction.transaction_form_factory
          - @bc_app_wallet_wallet.wallet_service_facade

    bc_app_wallet_transaction.create_controller:
        class: %bc_app_wallet_transaction.create_controller.class%
        arguments:
          - @security.token_storage
          - @templating
          - @translator
          - "@session"
          - @router
          - @bc_app_wallet_transaction.transaction_form_factory
          - @command_bus
          - @bc_app_wallet_wallet.wallet_service_facade

    # sercice facades

    # services

    # repositories

    bc_app_wallet_transaction.encrypted_transaction_repository:
        class: %bc_app_wallet_transaction.encrypted_transaction_repository.class%
        arguments:
          - %bc_app_wallet_address_flywheel_data_dir%

    bc_app_wallet_transaction.transaction_repository:
        class: %bc_app_wallet_transaction.transaction_repository.class%
        arguments:
          - @bc_app_wallet_transaction.encrypted_transaction_repository
          - @bc_app_common_infrastructure_app_common.encryptor
          - @bc_app_common_infrastructure_app_common.encryptor

    # command handlers

    bc_app_wallet_transaction.create_transaction_command_handler:
        class: %bc_app_wallet_transaction.create_transaction_command_handler.class%
        arguments:
            - @bc_app_wallet_wallet.wallet_repository
            - @bc_app_wallet_address.address_repository
            - @bc_app_wallet_transaction.transaction_repository
            - @bc_app_common_blockcypher.transaction_service
            - @bc_app_common_infrastructure_app_common.clock
        tags:
            - { name: command_handler, handles: bc_app_wallet_transaction_create_transaction }

    # form factory

    bc_app_wallet_transaction.transaction_form_factory:
        class: "%bc_app_wallet_transaction.transaction_form_factory.class%"
        public: false
        arguments:
            - @form.factory
            - @router
            - @translator
            - @bc_app_wallet_wallet.wallet_repository